
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-05T13:56:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dbb633179f366e6a7684f0dbe9f694940199974",
 "version": "0.2.4+3.g8dbb633"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
